# Generated by Django 4.0.1 on 2022-02-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_posts_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
